In [415]:
import pandas as pd
import numpy as np

df_activite = pd.read_csv("arrets-de-travail-par-secteur-d-activite-naf-1-et-naf-5.csv", sep=";")

print("Loaded successfully! Shape:", df_activite)

Loaded successfully! Shape:        annee code_NAF1                        libelle_NAF1  \
0       2015         A  Agriculture, sylviculture et pêche
1       2015         A  Agriculture, sylviculture et pêche
2       2015         A  Agriculture, sylviculture et pêche
3       2015         A  Agriculture, sylviculture et pêche
4       2015         A  Agriculture, sylviculture et pêche
...      ...       ...                                 ...
30235   2024         x                    Valeur manquante
30236   2024         x                    Valeur manquante
30237   2024         x                    Valeur manquante
30238   2024         x                    Valeur manquante
30239   2024         x                    Valeur manquante

                                         NAF1 code_NAF5  \
0      A - Agriculture, sylviculture et pêche     0111Z
1      A - Agriculture, sylviculture et pêche     0111Z
2      A - Agriculture, sylviculture et pêche     0111Z
3      A - Agriculture, sylviculture et pêche     0111Z
4      A - Agriculture, sylviculture et pêche     0112Z
...                                       ...       ...
30235                    x - Valeur manquante      TOUS
30236                    x - Valeur manquante     xxxxx
30237                    x - Valeur manquante     xxxxx
30238                    x - Valeur manquante     xxxxx
30239                    x - Valeur manquante     xxxxx

                                            libelle_NAF5  \
0      Culture de céréales (à l'exception du riz), de...
1      Culture de céréales (à l'exception du riz), de...
2      Culture de céréales (à l'exception du riz), de...
3      Culture de céréales (à l'exception du riz), de...
4                                         Culture du riz
...                                                  ...
30235                             Total Valeur manquante
30236                                   Valeur manquante
30237                                   Valeur manquante
30238                                   Valeur manquante
30239                                   Valeur manquante

                                                    NAF5  \
0      0111Z - Culture de céréales (à l'exception du ...
1      0111Z - Culture de céréales (à l'exception du ...
2      0111Z - Culture de céréales (à l'exception du ...
3      0111Z - Culture de céréales (à l'exception du ...
4                                 0112Z - Culture du riz
...                                                  ...
30235                             Total Valeur manquante
30236                           xxxxx - Valeur manquante
30237                           xxxxx - Valeur manquante
30238                           xxxxx - Valeur manquante
30239                           xxxxx - Valeur manquante

                          risque  nb_jours_arret_travail  \
0            Accidents de trajet                     0.0
1           Accidents du travail                   255.0
2      Maladies professionnelles                   318.0
3         Tous risques confondus                   573.0
4            Accidents de trajet                     0.0
...                          ...                     ...
30235     Tous risques confondus                830262.0
30236        Accidents de trajet                 43928.0
30237       Accidents du travail                106377.0
30238  Maladies professionnelles                679957.0
30239     Tous risques confondus                830262.0

      nb_jours_arret_travail_txt
0                              0
1                            255
2                            318
3                            573
4                              0
...                          ...
30235                     830262
30236                      43928
30237                     106377
30238                     679957
30239                     830262

[30240 rows x 10 columns]

In [416]:
df_activite

,annee,code_NAF1,libelle_NAF1,NAF1,code_NAF5,libelle_NAF5,NAF5,risque,nb_jours_arret_travail,nb_jours_arret_travail_txt
0,2015,A,"Agriculture, sylviculture et pêche","A - Agriculture, sylviculture et pêche",0111Z,"Culture de céréales (à l'exception du riz), de...",0111Z - Culture de céréales (à l'exception du ...,Accidents de trajet,0.0,0
1,2015,A,"Agriculture, sylviculture et pêche","A - Agriculture, sylviculture et pêche",0111Z,"Culture de céréales (à l'exception du riz), de...",0111Z - Culture de céréales (à l'exception du ...,Accidents du travail,255.0,255
2,2015,A,"Agriculture, sylviculture et pêche","A - Agriculture, sylviculture et pêche",0111Z,"Culture de céréales (à l'exception du riz), de...",0111Z - Culture de céréales (à l'exception du ...,Maladies professionnelles,318.0,318
3,2015,A,"Agriculture, sylviculture et pêche","A - Agriculture, sylviculture et pêche",0111Z,"Culture de céréales (à l'exception du riz), de...",0111Z - Culture de céréales (à l'exception du ...,Tous risques confondus,573.0,573
4,2015,A,"Agriculture, sylviculture et pêche","A - Agriculture, sylviculture et pêche",0112Z,Culture du riz,0112Z - Culture du riz,Accidents de trajet,0.0,0
...,...,...,...,...,...,...,...,...,...,...
30235,2024,x,Valeur manquante,x - Valeur manquante,TOUS,Total Valeur manquante,Total Valeur manquante,Tous risques confondus,830262.0,830262
30236,2024,x,Valeur manquante,x - Valeur manquante,xxxxx,Valeur manquante,xxxxx - Valeur manquante,Accidents de trajet,43928.0,43928
30237,2024,x,Valeur manquante,x - Valeur manquante,xxxxx,Valeur manquante,xxxxx - Valeur manquante,Accidents du travail,106377.0,106377
30238,2024,x,Valeur manquante,x - Valeur manquante,xxxxx,Valeur manquante,xxxxx - Valeur manquante,Maladies professionnelles,679957.0,679957
30239,2024,x,Valeur manquante,x - Valeur manquante,xxxxx,Valeur manquante,xxxxx - Valeur manquante,Tous risques confondus,830262.0,830262

In [417]:
df_activite.describe()

              annee  nb_jours_arret_travail
count  30240.000000            2.956500e+04
mean    2019.500000            1.332736e+05
std        2.872329            1.608434e+06
min     2015.000000            0.000000e+00
25%     2017.000000            1.377000e+03
50%     2019.500000            6.873000e+03
75%     2022.000000            3.021000e+04
max     2024.000000            7.888625e+07

In [418]:
df_activite.drop(columns=["NAF1","code_NAF1","libelle_NAF1","NAF5","nb_jours_arret_travail_txt"], inplace=True)

In [419]:
df_activite

,annee,code_NAF5,libelle_NAF5,risque,nb_jours_arret_travail
0,2015,0111Z,"Culture de céréales (à l'exception du riz), de...",Accidents de trajet,0.0
1,2015,0111Z,"Culture de céréales (à l'exception du riz), de...",Accidents du travail,255.0
2,2015,0111Z,"Culture de céréales (à l'exception du riz), de...",Maladies professionnelles,318.0
3,2015,0111Z,"Culture de céréales (à l'exception du riz), de...",Tous risques confondus,573.0
4,2015,0112Z,Culture du riz,Accidents de trajet,0.0
...,...,...,...,...,...
30235,2024,TOUS,Total Valeur manquante,Tous risques confondus,830262.0
30236,2024,xxxxx,Valeur manquante,Accidents de trajet,43928.0
30237,2024,xxxxx,Valeur manquante,Accidents du travail,106377.0
30238,2024,xxxxx,Valeur manquante,Maladies professionnelles,679957.0
30239,2024,xxxxx,Valeur manquante,Tous risques confondus,830262.0

In [420]:
#supprimer les ligne où risuqe = tous risuqe confondus et où code_NAF5 = xxxxx
# Filtrage AVANT de supprimer la colonne "risque"
df_activite = df_activite[
    (df_activite["risque"] != "Tous risques confondus") &
    (df_activite["code_NAF5"] != "xxxxx")
]

# Suppression des lignes "agrégées" ou non pertinentes :
df_activite = df_activite[
    (df_activite["risque"] != "Tous risques confondus") &      # on exclut les lignes "total tous risques"
    (~df_activite["code_NAF5"].isin(["xxxxx", "TOUS"]))        # on exclut les codes secteur agrégés/manquants
]

In [421]:
df_activite

,annee,code_NAF5,libelle_NAF5,risque,nb_jours_arret_travail
0,2015,0111Z,"Culture de céréales (à l'exception du riz), de...",Accidents de trajet,0.0
1,2015,0111Z,"Culture de céréales (à l'exception du riz), de...",Accidents du travail,255.0
2,2015,0111Z,"Culture de céréales (à l'exception du riz), de...",Maladies professionnelles,318.0
4,2015,0112Z,Culture du riz,Accidents de trajet,0.0
5,2015,0112Z,Culture du riz,Accidents du travail,0.0
...,...,...,...,...,...
30213,2024,9820Z,Activités indifférenciées des ménages en tant ...,Accidents du travail,0.0
30214,2024,9820Z,Activités indifférenciées des ménages en tant ...,Maladies professionnelles,0.0
30224,2024,9900Z,Activités des organisations et organismes extr...,Accidents de trajet,4086.0
30225,2024,9900Z,Activités des organisations et organismes extr...,Accidents du travail,9692.0
30226,2024,9900Z,Activités des organisations et organismes extr...,Maladies professionnelles,2693.0

In [422]:
df_activite.shape

(21960, 5)

In [423]:
print("Le pourcentage des valeures manquantes \n",(df_activite.isna().mean() * 100).round(1).sort_values(ascending=False),"\n\n")

Le pourcentage des valeures manquantes
 nb_jours_arret_travail    2.1
annee                     0.0
code_NAF5                 0.0
libelle_NAF5              0.0
risque                    0.0
dtype: float64

In [424]:
df_cause = pd.read_csv("causes-des-accidents-de-trajet-par-secteur-d-activite-naf-1-et-naf-5.csv", sep=";")

In [425]:
df_cause

,annee,code_NAF1,libelle_NAF1,NAF1,code_NAF5,libelle_NAF5,NAF5,libelle_cause_TR,libelle_type_vehicule,part_cause_TR,part_cause_tr_txt
0,2015,A,"Agriculture, sylviculture et pêche","A - Agriculture, sylviculture et pêche",0111Z,"Culture de céréales (à l'exception du riz), de...",0111Z - Culture de céréales (à l'exception du ...,Autres causes,NaN,NaN,NC
1,2015,A,"Agriculture, sylviculture et pêche","A - Agriculture, sylviculture et pêche",0111Z,"Culture de céréales (à l'exception du riz), de...",0111Z - Culture de céréales (à l'exception du ...,Chute de hauteur,NaN,NaN,NC
2,2015,A,"Agriculture, sylviculture et pêche","A - Agriculture, sylviculture et pêche",0111Z,"Culture de céréales (à l'exception du riz), de...",0111Z - Culture de céréales (à l'exception du ...,Entrainé par quelque chose ou quelqu'un,NaN,NaN,NC
3,2015,A,"Agriculture, sylviculture et pêche","A - Agriculture, sylviculture et pêche",0111Z,"Culture de céréales (à l'exception du riz), de...",0111Z - Culture de céréales (à l'exception du ...,Geste intempestif,NaN,NaN,NC
4,2015,A,"Agriculture, sylviculture et pêche","A - Agriculture, sylviculture et pêche",0111Z,"Culture de céréales (à l'exception du riz), de...",0111Z - Culture de céréales (à l'exception du ...,Perte d'équilibre avec chute,NaN,NaN,NC
...,...,...,...,...,...,...,...,...,...,...,...
98275,2024,x,Valeur manquante,x - Valeur manquante,xxxxx,Valeur manquante,xxxxx - Valeur manquante,Perte de contrôle d'un véhicule,Tous types de véhicules confondus,50.0,0.5
98276,2024,x,Valeur manquante,x - Valeur manquante,xxxxx,Valeur manquante,xxxxx - Valeur manquante,Perte de contrôle d'un véhicule,"Vélo, trottinette",50.0,0.5
98277,2024,x,Valeur manquante,x - Valeur manquante,xxxxx,Valeur manquante,xxxxx - Valeur manquante,Perte de contrôle d'un véhicule,Voiture,50.0,0.5
98278,2024,x,Valeur manquante,x - Valeur manquante,xxxxx,Valeur manquante,xxxxx - Valeur manquante,Toutes causes confondues,NaN,100.0,1
98279,2024,x,Valeur manquante,x - Valeur manquante,xxxxx,Valeur manquante,xxxxx - Valeur manquante,Violence et agression,NaN,0.0,0

In [426]:
print("Le pourcentage des valeures manquantes \n",(df_cause.isna().mean() * 100).round(1).sort_values(ascending=False),"\n\n")

Le pourcentage des valeures manquantes
 libelle_type_vehicule    61.5
part_cause_TR            12.1
annee                     0.0
libelle_NAF1              0.0
code_NAF1                 0.0
NAF1                      0.0
code_NAF5                 0.0
NAF5                      0.0
libelle_NAF5              0.0
libelle_cause_TR          0.0
part_cause_tr_txt         0.0
dtype: float64

In [427]:
df_cause.drop(columns=["NAF1","code_NAF1","libelle_NAF1","NAF5","libelle_type_vehicule","part_cause_TR","part_cause_tr_txt"], inplace=True)

In [428]:
df_cause

,annee,code_NAF5,libelle_NAF5,libelle_cause_TR
0,2015,0111Z,"Culture de céréales (à l'exception du riz), de...",Autres causes
1,2015,0111Z,"Culture de céréales (à l'exception du riz), de...",Chute de hauteur
2,2015,0111Z,"Culture de céréales (à l'exception du riz), de...",Entrainé par quelque chose ou quelqu'un
3,2015,0111Z,"Culture de céréales (à l'exception du riz), de...",Geste intempestif
4,2015,0111Z,"Culture de céréales (à l'exception du riz), de...",Perte d'équilibre avec chute
...,...,...,...,...
98275,2024,xxxxx,Valeur manquante,Perte de contrôle d'un véhicule
98276,2024,xxxxx,Valeur manquante,Perte de contrôle d'un véhicule
98277,2024,xxxxx,Valeur manquante,Perte de contrôle d'un véhicule
98278,2024,xxxxx,Valeur manquante,Toutes causes confondues
98279,2024,xxxxx,Valeur manquante,Violence et agression

In [429]:
# Filtrage AVANT de supprimer la colonne "risque"
df_cause = df_cause[
    
    (df_cause["code_NAF5"] != "xxxxx")
]

# Suppression des lignes "agrégées" ou non pertinentes :
df_cause = df_cause[
         (~df_cause["code_NAF5"].isin(["xxxxx", "TOUS"]))]

In [430]:
df_cause

,annee,code_NAF5,libelle_NAF5,libelle_cause_TR
0,2015,0111Z,"Culture de céréales (à l'exception du riz), de...",Autres causes
1,2015,0111Z,"Culture de céréales (à l'exception du riz), de...",Chute de hauteur
2,2015,0111Z,"Culture de céréales (à l'exception du riz), de...",Entrainé par quelque chose ou quelqu'un
3,2015,0111Z,"Culture de céréales (à l'exception du riz), de...",Geste intempestif
4,2015,0111Z,"Culture de céréales (à l'exception du riz), de...",Perte d'équilibre avec chute
...,...,...,...,...
98236,2024,9900Z,Activités des organisations et organismes extr...,Perte de contrôle d'un véhicule
98237,2024,9900Z,Activités des organisations et organismes extr...,Perte de contrôle d'un véhicule
98238,2024,9900Z,Activités des organisations et organismes extr...,Perte de contrôle d'un véhicule
98239,2024,9900Z,Activités des organisations et organismes extr...,Toutes causes confondues
98240,2024,9900Z,Activités des organisations et organismes extr...,Violence et agression

In [431]:
#supprimer les lignes où libelle_cause_TR = "Toutes causes confondues"
df_cause = df_cause[df_cause["libelle_cause_TR"] != "Toutes causes confondues"]
df_cause

,annee,code_NAF5,libelle_NAF5,libelle_cause_TR
0,2015,0111Z,"Culture de céréales (à l'exception du riz), de...",Autres causes
1,2015,0111Z,"Culture de céréales (à l'exception du riz), de...",Chute de hauteur
2,2015,0111Z,"Culture de céréales (à l'exception du riz), de...",Entrainé par quelque chose ou quelqu'un
3,2015,0111Z,"Culture de céréales (à l'exception du riz), de...",Geste intempestif
4,2015,0111Z,"Culture de céréales (à l'exception du riz), de...",Perte d'équilibre avec chute
...,...,...,...,...
98235,2024,9900Z,Activités des organisations et organismes extr...,Perte de contrôle d'un véhicule
98236,2024,9900Z,Activités des organisations et organismes extr...,Perte de contrôle d'un véhicule
98237,2024,9900Z,Activités des organisations et organismes extr...,Perte de contrôle d'un véhicule
98238,2024,9900Z,Activités des organisations et organismes extr...,Perte de contrôle d'un véhicule
98240,2024,9900Z,Activités des organisations et organismes extr...,Violence et agression

In [432]:


# fusionner les lignes où libelle_cause_TR = "Perte de contrôle d'un véhicule" en une seule ligne par groupe
df_cause = df_cause.drop_duplicates()
df_cause

,annee,code_NAF5,libelle_NAF5,libelle_cause_TR
0,2015,0111Z,"Culture de céréales (à l'exception du riz), de...",Autres causes
1,2015,0111Z,"Culture de céréales (à l'exception du riz), de...",Chute de hauteur
2,2015,0111Z,"Culture de céréales (à l'exception du riz), de...",Entrainé par quelque chose ou quelqu'un
3,2015,0111Z,"Culture de céréales (à l'exception du riz), de...",Geste intempestif
4,2015,0111Z,"Culture de céréales (à l'exception du riz), de...",Perte d'équilibre avec chute
...,...,...,...,...
98231,2024,9900Z,Activités des organisations et organismes extr...,Geste intempestif
98232,2024,9900Z,Activités des organisations et organismes extr...,Perte d'équilibre avec chute
98233,2024,9900Z,Activités des organisations et organismes extr...,Perte d'équilibre sans chute
98234,2024,9900Z,Activités des organisations et organismes extr...,Perte de contrôle d'un véhicule
98240,2024,9900Z,Activités des organisations et organismes extr...,Violence et agression

In [433]:
df_depense=pd.read_csv("depenses-par-poste.csv", sep=";")
df_depense

,annee,risque,poste_depenses,montant_depenses
0,2015,Accidents de trajet,"Frais de santé (frais médicaux, pharmacie, hos...",123156675
1,2015,Accidents de trajet,"Indemnités en capital, rentes, capital décès",354465828
2,2015,Accidents de trajet,Indemnités journalières,283865550
3,2015,Accidents de trajet,Tous postes de dépense confondus,761488053
4,2015,Accidents du travail,"Frais de santé (frais médicaux, pharmacie, hos...",493383039
...,...,...,...,...
155,2024,Maladies professionnelles,Tous postes de dépense confondus,3229187237
156,2024,Tous risques confondus,"Frais de santé (frais médicaux, pharmacie, hos...",785282153
157,2024,Tous risques confondus,"Indemnités en capital, rentes, capital décès",4386200650
158,2024,Tous risques confondus,Indemnités journalières,4795933080
159,2024,Tous risques confondus,Tous postes de dépense confondus,9967415883

In [434]:
df_depense.describe()

             annee  montant_depenses
count   160.000000      1.600000e+02
mean   2019.500000      1.948573e+09
std       2.881299      2.045249e+09
min    2015.000000      5.398085e+07
25%    2017.000000      4.580819e+08
50%    2019.500000      1.104676e+09
75%    2022.000000      2.905951e+09
max    2024.000000      9.967416e+09

In [435]:
df_depense

,annee,risque,poste_depenses,montant_depenses
0,2015,Accidents de trajet,"Frais de santé (frais médicaux, pharmacie, hos...",123156675
1,2015,Accidents de trajet,"Indemnités en capital, rentes, capital décès",354465828
2,2015,Accidents de trajet,Indemnités journalières,283865550
3,2015,Accidents de trajet,Tous postes de dépense confondus,761488053
4,2015,Accidents du travail,"Frais de santé (frais médicaux, pharmacie, hos...",493383039
...,...,...,...,...
155,2024,Maladies professionnelles,Tous postes de dépense confondus,3229187237
156,2024,Tous risques confondus,"Frais de santé (frais médicaux, pharmacie, hos...",785282153
157,2024,Tous risques confondus,"Indemnités en capital, rentes, capital décès",4386200650
158,2024,Tous risques confondus,Indemnités journalières,4795933080
159,2024,Tous risques confondus,Tous postes de dépense confondus,9967415883

In [436]:
#supprimer les lignes où poste_depenses = "Tous postes de dépense confondus"
df_depense = df_depense[df_depense["poste_depenses"] != "Tous postes de dépense confondus"]
df_depense

,annee,risque,poste_depenses,montant_depenses
0,2015,Accidents de trajet,"Frais de santé (frais médicaux, pharmacie, hos...",123156675
1,2015,Accidents de trajet,"Indemnités en capital, rentes, capital décès",354465828
2,2015,Accidents de trajet,Indemnités journalières,283865550
4,2015,Accidents du travail,"Frais de santé (frais médicaux, pharmacie, hos...",493383039
5,2015,Accidents du travail,"Indemnités en capital, rentes, capital décès",1141478870
...,...,...,...,...
153,2024,Maladies professionnelles,"Indemnités en capital, rentes, capital décès",2073170156
154,2024,Maladies professionnelles,Indemnités journalières,1077438175
156,2024,Tous risques confondus,"Frais de santé (frais médicaux, pharmacie, hos...",785282153
157,2024,Tous risques confondus,"Indemnités en capital, rentes, capital décès",4386200650
158,2024,Tous risques confondus,Indemnités journalières,4795933080

In [437]:
df_depense.info()

<class 'pandas.DataFrame'>
Index: 120 entries, 0 to 158
Data columns (total 4 columns):
 #   Column            Non-Null Count  Dtype
---  ------            --------------  -----
 0   annee             120 non-null    int64
 1   risque            120 non-null    str
 2   poste_depenses    120 non-null    str
 3   montant_depenses  120 non-null    int64
dtypes: int64(2), str(2)
memory usage: 4.7 KB

In [438]:
df_region = pd.read_csv("sinistralite-par-region-administrative.csv", sep=";")

df_region

,annee,code_region_admin,libelle_region_admin,risque,nb_sinistres,nb_salaries,indice_frequence,nb_sinistres_int,indice_frequence_int
0,2005,1,Guadeloupe,Accidents de trajet,214,86011,"2,5",214,2.5
1,2005,1,Guadeloupe,Accidents du travail,1396,86011,"16,2",1396,16.2
2,2005,1,Guadeloupe,Maladies professionnelles,20,86011,NC,20,NaN
3,2005,1,Guadeloupe,Tous risques confondus,1630,86011,NC,1630,NaN
4,2005,2,Martinique,Accidents de trajet,185,89687,"2,1",185,2.1
...,...,...,...,...,...,...,...,...,...
1515,2024,94,Corse,Tous risques confondus,3729,94556,NC,3729,NaN
1516,2024,99,FRANCE,Accidents de trajet,94431,20798997,"4,5",94431,4.5
1517,2024,99,FRANCE,Accidents du travail,548550,20798997,"26,4",548550,26.4
1518,2024,99,FRANCE,Maladies professionnelles,48036,20798997,NC,48036,NaN
1519,2024,99,FRANCE,Tous risques confondus,691017,20798997,NC,691017,NaN

In [439]:
df_region.drop(columns=["code_region_admin","nb_sinistres","indice_frequence","indice_frequence_int"], inplace=True)

In [440]:


df_region = df_region[df_region["risque"] != "Tous risques confondus"]

df_region

,annee,libelle_region_admin,risque,nb_salaries,nb_sinistres_int
0,2005,Guadeloupe,Accidents de trajet,86011,214
1,2005,Guadeloupe,Accidents du travail,86011,1396
2,2005,Guadeloupe,Maladies professionnelles,86011,20
4,2005,Martinique,Accidents de trajet,89687,185
5,2005,Martinique,Accidents du travail,89687,1520
...,...,...,...,...,...
1513,2024,Corse,Accidents du travail,94556,3118
1514,2024,Corse,Maladies professionnelles,94556,186
1516,2024,FRANCE,Accidents de trajet,20798997,94431
1517,2024,FRANCE,Accidents du travail,20798997,548550
1518,2024,FRANCE,Maladies professionnelles,20798997,48036

In [441]:
df_region.describe()

             annee   nb_salaries  nb_sinistres_int
count  1140.000000  1.140000e+03       1140.000000
mean   2014.500000  2.016274e+06      26763.582456
std       5.768812  4.191147e+06      85050.616932
min    2005.000000  0.000000e+00          0.000000
25%    2009.750000  9.794250e+04       1160.750000
50%    2014.500000  9.071485e+05       4027.000000
75%    2019.250000  1.500785e+06      25982.000000
max    2024.000000  2.079900e+07     717394.000000

In [442]:
df_region.info()

<class 'pandas.DataFrame'>
Index: 1140 entries, 0 to 1518
Data columns (total 5 columns):
 #   Column                Non-Null Count  Dtype
---  ------                --------------  -----
 0   annee                 1140 non-null   int64
 1   libelle_region_admin  1140 non-null   str
 2   risque                1140 non-null   str
 3   nb_salaries           1140 non-null   int64
 4   nb_sinistres_int      1140 non-null   int64
dtypes: int64(3), str(2)
memory usage: 53.4 KB

In [443]:
df_hf=pd.read_csv("troubles-musculosquelettiques-par-partie-du-corps-sexe-et-secteur-d-activite-naf-1-et-naf-5.csv", sep=";")
df_hf

,annee,code_NAF1,libelle_NAF1,NAF1,code_NAF5,libelle_NAF5,NAF5,sexe,code_partie_corps,partie_corps,part_TMS,part_tms_int
0,2015,A,"Agriculture, sylviculture et pêche","A - Agriculture, sylviculture et pêche",0111Z,"Culture de céréales (à l'exception du riz), de...",0111Z - Culture de céréales (à l'exception du ...,Femmes,A,épaule,NC,NaN
1,2015,A,"Agriculture, sylviculture et pêche","A - Agriculture, sylviculture et pêche",0111Z,"Culture de céréales (à l'exception du riz), de...",0111Z - Culture de céréales (à l'exception du ...,Femmes,B,coude,NC,NaN
2,2015,A,"Agriculture, sylviculture et pêche","A - Agriculture, sylviculture et pêche",0111Z,"Culture de céréales (à l'exception du riz), de...",0111Z - Culture de céréales (à l'exception du ...,Femmes,C,"poignet, main, doigt",NC,NaN
3,2015,A,"Agriculture, sylviculture et pêche","A - Agriculture, sylviculture et pêche",0111Z,"Culture de céréales (à l'exception du riz), de...",0111Z - Culture de céréales (à l'exception du ...,Femmes,D,genou,NC,NaN
4,2015,A,"Agriculture, sylviculture et pêche","A - Agriculture, sylviculture et pêche",0111Z,"Culture de céréales (à l'exception du riz), de...",0111Z - Culture de céréales (à l'exception du ...,Femmes,E,"cheville, pied",NC,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...
181435,2024,x,Valeur manquante,x - Valeur manquante,xxxxx,Valeur manquante,xxxxx - Valeur manquante,Tous sexes,D,genou,0.02,0.02
181436,2024,x,Valeur manquante,x - Valeur manquante,xxxxx,Valeur manquante,xxxxx - Valeur manquante,Tous sexes,E,"cheville, pied",0,0.00
181437,2024,x,Valeur manquante,x - Valeur manquante,xxxxx,Valeur manquante,xxxxx - Valeur manquante,Tous sexes,F,dos,0.06,0.06
181438,2024,x,Valeur manquante,x - Valeur manquante,xxxxx,Valeur manquante,xxxxx - Valeur manquante,Tous sexes,TOUT,corps entier,1,1.00
181439,2024,x,Valeur manquante,x - Valeur manquante,xxxxx,Valeur manquante,xxxxx - Valeur manquante,Tous sexes,Z,association de plusieurs syndromes du tableau,0,0.00

In [444]:
df_partie = df_hf[["annee","code_NAF5","libelle_NAF5","partie_corps"]]
df_partie

,annee,code_NAF5,libelle_NAF5,partie_corps
0,2015,0111Z,"Culture de céréales (à l'exception du riz), de...",épaule
1,2015,0111Z,"Culture de céréales (à l'exception du riz), de...",coude
2,2015,0111Z,"Culture de céréales (à l'exception du riz), de...","poignet, main, doigt"
3,2015,0111Z,"Culture de céréales (à l'exception du riz), de...",genou
4,2015,0111Z,"Culture de céréales (à l'exception du riz), de...","cheville, pied"
...,...,...,...,...
181435,2024,xxxxx,Valeur manquante,genou
181436,2024,xxxxx,Valeur manquante,"cheville, pied"
181437,2024,xxxxx,Valeur manquante,dos
181438,2024,xxxxx,Valeur manquante,corps entier
181439,2024,xxxxx,Valeur manquante,association de plusieurs syndromes du tableau

In [445]:
df_partie= df_partie[
    ~df_partie["code_NAF5"].isin(["xxxxx", "TOUS"]) ]
df_partie

,annee,code_NAF5,libelle_NAF5,partie_corps
0,2015,0111Z,"Culture de céréales (à l'exception du riz), de...",épaule
1,2015,0111Z,"Culture de céréales (à l'exception du riz), de...",coude
2,2015,0111Z,"Culture de céréales (à l'exception du riz), de...","poignet, main, doigt"
3,2015,0111Z,"Culture de céréales (à l'exception du riz), de...",genou
4,2015,0111Z,"Culture de céréales (à l'exception du riz), de...","cheville, pied"
...,...,...,...,...
181363,2024,9900Z,Activités des organisations et organismes extr...,genou
181364,2024,9900Z,Activités des organisations et organismes extr...,"cheville, pied"
181365,2024,9900Z,Activités des organisations et organismes extr...,dos
181366,2024,9900Z,Activités des organisations et organismes extr...,corps entier
181367,2024,9900Z,Activités des organisations et organismes extr...,association de plusieurs syndromes du tableau

In [446]:
df_partie = df_partie.drop_duplicates()
df_partie

,annee,code_NAF5,libelle_NAF5,partie_corps
0,2015,0111Z,"Culture de céréales (à l'exception du riz), de...",épaule
1,2015,0111Z,"Culture de céréales (à l'exception du riz), de...",coude
2,2015,0111Z,"Culture de céréales (à l'exception du riz), de...","poignet, main, doigt"
3,2015,0111Z,"Culture de céréales (à l'exception du riz), de...",genou
4,2015,0111Z,"Culture de céréales (à l'exception du riz), de...","cheville, pied"
...,...,...,...,...
181347,2024,9900Z,Activités des organisations et organismes extr...,genou
181348,2024,9900Z,Activités des organisations et organismes extr...,"cheville, pied"
181349,2024,9900Z,Activités des organisations et organismes extr...,dos
181350,2024,9900Z,Activités des organisations et organismes extr...,corps entier
181351,2024,9900Z,Activités des organisations et organismes extr...,association de plusieurs syndromes du tableau

In [447]:
df_hf.drop(columns=["NAF1","code_NAF1","libelle_NAF1","NAF5","code_partie_corps","partie_corps","part_TMS","part_tms_int"], inplace=True)

In [448]:
df_hf

,annee,code_NAF5,libelle_NAF5,sexe
0,2015,0111Z,"Culture de céréales (à l'exception du riz), de...",Femmes
1,2015,0111Z,"Culture de céréales (à l'exception du riz), de...",Femmes
2,2015,0111Z,"Culture de céréales (à l'exception du riz), de...",Femmes
3,2015,0111Z,"Culture de céréales (à l'exception du riz), de...",Femmes
4,2015,0111Z,"Culture de céréales (à l'exception du riz), de...",Femmes
...,...,...,...,...
181435,2024,xxxxx,Valeur manquante,Tous sexes
181436,2024,xxxxx,Valeur manquante,Tous sexes
181437,2024,xxxxx,Valeur manquante,Tous sexes
181438,2024,xxxxx,Valeur manquante,Tous sexes
181439,2024,xxxxx,Valeur manquante,Tous sexes

In [449]:
df_hf= df_hf[
    ~df_hf["code_NAF5"].isin(["xxxxx", "TOUS"]) &
    (df_hf["sexe"] != "Tous sexes")
]

In [450]:
df_hf

,annee,code_NAF5,libelle_NAF5,sexe
0,2015,0111Z,"Culture de céréales (à l'exception du riz), de...",Femmes
1,2015,0111Z,"Culture de céréales (à l'exception du riz), de...",Femmes
2,2015,0111Z,"Culture de céréales (à l'exception du riz), de...",Femmes
3,2015,0111Z,"Culture de céréales (à l'exception du riz), de...",Femmes
4,2015,0111Z,"Culture de céréales (à l'exception du riz), de...",Femmes
...,...,...,...,...
181355,2024,9900Z,Activités des organisations et organismes extr...,Hommes
181356,2024,9900Z,Activités des organisations et organismes extr...,Hommes
181357,2024,9900Z,Activités des organisations et organismes extr...,Hommes
181358,2024,9900Z,Activités des organisations et organismes extr...,Hommes
181359,2024,9900Z,Activités des organisations et organismes extr...,Hommes

In [451]:
df_hf = df_hf.drop_duplicates()
   
df_hf

,annee,code_NAF5,libelle_NAF5,sexe
0,2015,0111Z,"Culture de céréales (à l'exception du riz), de...",Femmes
8,2015,0111Z,"Culture de céréales (à l'exception du riz), de...",Hommes
24,2015,0112Z,Culture du riz,Femmes
32,2015,0112Z,Culture du riz,Hommes
48,2015,0113Z,"Culture de légumes, de melons, de racines et d...",Femmes
...,...,...,...,...
181256,2024,9810Z,Activités indifférenciées des ménages en tant ...,Hommes
181272,2024,9820Z,Activités indifférenciées des ménages en tant ...,Femmes
181280,2024,9820Z,Activités indifférenciées des ménages en tant ...,Hommes
181344,2024,9900Z,Activités des organisations et organismes extr...,Femmes
181352,2024,9900Z,Activités des organisations et organismes extr...,Hommes

In [452]:
df_hf

,annee,code_NAF5,libelle_NAF5,sexe
0,2015,0111Z,"Culture de céréales (à l'exception du riz), de...",Femmes
8,2015,0111Z,"Culture de céréales (à l'exception du riz), de...",Hommes
24,2015,0112Z,Culture du riz,Femmes
32,2015,0112Z,Culture du riz,Hommes
48,2015,0113Z,"Culture de légumes, de melons, de racines et d...",Femmes
...,...,...,...,...
181256,2024,9810Z,Activités indifférenciées des ménages en tant ...,Hommes
181272,2024,9820Z,Activités indifférenciées des ménages en tant ...,Femmes
181280,2024,9820Z,Activités indifférenciées des ménages en tant ...,Hommes
181344,2024,9900Z,Activités des organisations et organismes extr...,Femmes
181352,2024,9900Z,Activités des organisations et organismes extr...,Hommes

In [453]:
df_activite.to_csv("df_activite-nettoye.csv", sep=";", index=False)
print("df_activite enregistré avec succès !")

df_depense.to_csv("df_depense-nettoye.csv", sep=";", index=False)
print("df_depense enregistré avec succès !")

df_region.to_csv("df_region-nettoye.csv", sep=";", index=False)
print("df_region enregistré avec succès !")

df_cause.to_csv("df_cause-nettoye.csv", sep=";", index=False)
print("df_cause enregistré avec succès !")

df_partie.to_csv("df_partie-nettoye.csv", sep=";", index=False)
print("df_partie enregistré avec succès !")

df_hf.to_csv("df_hf-nettoye.csv", sep=";", index=False)
print("df_hf enregistré avec succès !")

df_activite enregistré avec succès !
df_depense enregistré avec succès !
df_region enregistré avec succès !
df_cause enregistré avec succès !
df_partie enregistré avec succès !
df_hf enregistré avec succès !